[package]
name = "rapi"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["image", "debug", "tokio"]}
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
